apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels: 
    app: flask
spec:
  replicas: 10
  selector:
    matchLabels:
      app: flask
  strategy:
    rollingUpdates:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: bethanpickering/trio-task-flaskapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5000  
    targetPort: 5000